nodeLinker: pnp

packageExtensions:
  "@backstage/cli@*":
    dependencies:
      jest-environment-node: "*"
      jest-environment-jsdom: "*"
  # createBackend resolves package paths into backend-defaults from plugin-api.
  "@backstage/backend-plugin-api@*":
    dependencies:
      "@backstage/backend-defaults": "*"
  "grpc-js-reflection-client@*":
    peerDependencies:
      "@grpc/grpc-js": "*"
      "@grpc/proto-loader": "*"
    dependencies:
      "@grpc/proto-loader": "*"
